services:
  - type: web
    name: whitehouse-feed-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false